# Generated by Django 5.2.5 on 2025-09-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educhatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='was_helpful',
            new_name='helpful',
        ),
    ]
