# Generated by Django 5.2.5 on 2025-10-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educhatbot', '0002_rename_was_helpful_feedback_helpful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='chatbot_response',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_message',
        ),
        migrations.AddField(
            model_name='feedback',
            name='bot_answer',
            field=models.TextField(blank=True, default='', help_text='Resposta do bot que foi avaliada.'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='session_id',
            field=models.BigIntegerField(blank=True, help_text='ID da sessão no momento do feedback (opcional).', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_question',
            field=models.TextField(blank=True, default='', help_text='Pergunta do usuário no momento do feedback.'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='helpful',
            field=models.BooleanField(help_text='True = ajudou (like), False = não ajudou (dislike).'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
