# Generated by Django 5.2.5 on 2025-10-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educhatbot', '0003_remove_feedback_chatbot_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='helpful',
            field=models.BooleanField(help_text='True = ajudou (like), False = não ajudou (dislike).', null=True),
        ),
    ]
