# Generated by Django 5.2.5 on 2025-10-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educhatbot', '0004_alter_feedback_helpful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='helpful',
            field=models.BooleanField(blank=True, help_text='True = ajudou (like), False = não ajudou (dislike).', null=True),
        ),
    ]
