# Generated by Django 5.2.5 on 2025-10-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educhatbot', '0005_alter_feedback_helpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='consumed',
            field=models.BooleanField(default=False, help_text='Se o backend já usou este feedback para adaptar a resposta.'),
        ),
    ]
