# Generated by Django 5.2.5 on 2025-11-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educhatbot', '0006_feedback_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='detected_intent',
            field=models.CharField(blank=True, help_text='Intent que o NLU detectou quando essa resposta foi gerada.', max_length=80, null=True),
        ),
    ]
