# Generated by Django 5.2.5 on 2025-11-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educhatbot', '0007_feedback_detected_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='bot_answer',
            field=models.TextField(blank=True, default='', help_text='Resposta do bot que foi avaliada.', max_length=8000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_question',
            field=models.TextField(blank=True, default='', help_text='Pergunta do usuário no momento do feedback.', max_length=8000),
        ),
    ]
